stages:
  - test
run_tests:
  stage: test
  image: python:3.12.3-bookworm
  before_script:
    - apt-get update && apt-get install -y python3-pip
    - pip install -Ur src/requirements.txt
  script:
    - pytest -v src